# Generated by Django 5.0.6 on 2024-06-10 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone',
            new_name='phone_number',
        ),
    ]
